// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using weGOPAY.weGOPAY.Data;

namespace weGOPAY.Migrations
{
    [DbContext(typeof(weGOPAYDbContext))]
    partial class weGOPAYDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.0-rtm-30799")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("weGOPAY.weGOPAY.Core.Models.Users.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CountryOfOrigin");

                    b.Property<string>("CountryOfResidence");

                    b.Property<DateTime>("DateRegistered");

                    b.Property<DateTime>("DateUpdated");

                    b.Property<string>("EmailAddress");

                    b.Property<string>("Fullname");

                    b.Property<string>("Gender");

                    b.Property<bool>("IsUpdated");

                    b.Property<byte[]>("PasswordHash");

                    b.Property<byte[]>("PasswordSalt");

                    b.Property<string>("Status");

                    b.Property<string>("UserId");

                    b.HasKey("Id");

                    b.ToTable("User");
                });

            modelBuilder.Entity("weGOPAY.weGOPAY.Core.Models.Wallets.Wallet", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("EuroBalance");

                    b.Property<decimal>("NairaBalance");

                    b.Property<decimal>("PoundBalance");

                    b.Property<string>("Status");

                    b.Property<decimal>("USDBalance");

                    b.Property<string>("UserId");

                    b.Property<DateTime>("WalletCreationDate");

                    b.Property<decimal>("YenBalance");

                    b.HasKey("Id");

                    b.ToTable("Wallet");
                });

            modelBuilder.Entity("weGOPAY.weGOPAY.Core.Models.WalletTransactions.WalletTransaction", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("Amount");

                    b.Property<int>("RequestCurrency");

                    b.Property<int>("ResponseCurrency");

                    b.Property<DateTime>("TransactionDate");

                    b.Property<int>("TransactionStatus");

                    b.Property<string>("UserId");

                    b.HasKey("Id");

                    b.ToTable("WalletTransaction");
                });
#pragma warning restore 612, 618
        }
    }
}
